# Generated by Django 4.2 on 2025-12-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(choices=[('hermosillo', 'Hermosillo'), ('guaymas', 'Guaymas'), ('nogales', 'Nogales'), ('obregon', 'Ciudad Obregón')], max_length=50)),
                ('tipo_dato', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('iluminacion', 'Iluminación')], max_length=50)),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
