# Generated by Django 4.2 on 2025-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosensor',
            name='municipio',
            field=models.CharField(choices=[('hermosillo', 'Hermosillo'), ('guaymas', 'Guaymas'), ('nogales', 'Nogales'), ('obregon', 'Ciudad Obregón'), ('empalme', 'Empalme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registrosensor',
            name='tipo_dato',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('uv', 'Índice UV')], max_length=20),
        ),
    ]
